<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "live_master"
 *
 * Auto generated by Extension Builder 2013-08-04
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'LiveMaster',
	'description' => '',
	'category' => 'plugin',
	'author' => 'Daniel Corn',
	'author_email' => 'info@cundd.net',
	'author_company' => 'cundd',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => 'typo3temp/livemaster',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '1.0.0',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.0',
			'fluid' => '6.0',
			'typo3' => '6.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>